fragment:
  version: 1
  name: roles/general-server
  description: Basic tools for a general-purpose Ubuntu server.

operations:
  - op: append
    path: /autoinstall/user-data/packages
    deduplicate: true
    value:
      - bind9-dnsutils
      - ca-certificates
      - curl
      - iputils-ping
      - vim-tiny

  - op: assert
    path: /autoinstall/user-data/packages
    type: list
